import type { Metadata } from "next";
import Footer from "@/components/layout/Credit";
import Title from '@/components/layout/Title'
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="vsc-initialized">
        <Title />
        {children}
        <Footer />
      </body>
    </html>
  );
}
